services:
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: arqui
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - app-network
  backend:
    container_name: backend
    build:
      context: ./App
    ports:
      - 5000:5000
  user:
    container_name: user
    build:
      context: ./User
    ports:
      - 5001:5000
    environment:
      - DEBUG=True
    volumes:
      - ./app:/app
    networks:
      - app-network
    depends_on:
      - db
    links:
      - db
  api:
    container_name: twitter_api
    build:
      context: ./TwitterAPI
    ports:
      - 5002:5000
    environment:
      - DEBUG=True
  aggregate:
    container_name: aggregate
    build:
      context: ./Aggregate
    ports:
      - 5003:5000
    environment:
      - DEBUG=True

#Docker Networks
networks:
  app-network:
    driver: bridge