version: "2"

services:

  db:
    image: mysql:5.7.22
    container_name: mysql_db
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: arqui
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    container_name: backend
    image: twiteer_endpoint_backend
    ports:
      - 5000:5000
    environment:
      - DEBUG=True
    networks:
      - app-network

  user:
    container_name: user
    image: twiteer_endpoint_user
    ports:
      - 5001:5000
    environment:
      - DEBUG=True
    networks:
      - app-network
    depends_on:
      - db

  api:
    container_name: twitter_api
    image: twiteer_endpoint_api
    ports:
      - 5002:5000
    environment:
      - DEBUG=True
    networks:
      - app-network

  aggregate:
    container_name: aggregate
    image: twiteer_endpoint_aggregate
    ports:
      - 5003:5000
    environment:
      - DEBUG=True
    networks:
      - app-network

volumes:
  db_data: {}
  
networks:
  app-network: