# syntax=docker/dockerfile:1

FROM python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install flask
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn  mysqlclient
RUN pip install flask-mysqldb
RUN pip install python-dotenv

COPY . .

CMD [ "python", "app.py"]